test_name: GSE68559   


raw_counts_script: "config/input_scripts/GSE68559.jl"
distributed: true

cache:
  keep_cache: true
  base_dir: "output/cache"
  clear:
    archive: false
    test_dir: false
    round_dir: false
    vst_dir: false
    clean_dir: false 
    norm_dir: false
    sampling_dir: false 
    similarity_dir: false 
    adjacency_dir: false  
    anal_dir: false 
    bio_dir: false
    community_dir: false 
    graphlet_counting_dir: false
    rep_dir: false 
    graphlet_enum_dir: false 
    coinc_dir: false 
    orbit_dir: false 

website:
  website: false
  page_name: "menu1"
  website_dir: "website"

data_preprocessing: 
  roundsig: 5 
  vst: true
  expression_cutoff: 0.05
  minreq: 0.05
  clean_method: "per-sample"
  norm_method: "median"
  variance_percent: 2.0
    
network_construction:
  construct: true
  coexpression: "pidc"
  nbins: "sqrt_n"  
  threshold: 0.95
  threshold_method: "empirical_dist_zero"
  visualise: false
  synthetic: false

analysis:    
  biological_validation: true
  community_detection: false
  wgcna: false
  func_annotate: false
  graphlet_counting: true
  graphlet_size: 4
  recursive: true #count lower graphlets as well
  typed_representation: true
  null_model_size: 1000
  coincident_graphlets: true
  
