test_name: GSE68559   


raw_counts_script: "config/input_scripts/GSE68559.jl"
distributed: true
cache:
  keep_cache: true
  base_dir: "output/cache"
  clear:
    archive: false
    test_dir: false
    cutoff_dir: false 
    norm_dir: false 
    sampling_dir: false 
    similarity_dir: false 
    adjacency_dir: false  
    anal_dir: false 
    bio_dir: false
    community_dir: false 
    graphlet_counting_dir: false
    rep_dir: false 
    graphlet_enum_dir: false 
    coinc_dir: false 
    orbit_dir: false 

website:
  website: true
  page_name: "menu1"
  website_dir: "website"

data_preprocessing: 
  expression_cutoff: 1
  norm_method: "upper_quartile"
  variance_percent: 0.025
    
network_construction:
  coexpression: "pidc"
  nbins: "sqrt_n"  
  threshold: 0.95
  threshold_method: "empirical_dist_zero"
  visualise: false
  synthetic: false

analysis:    
  biological_validation: true
  community_detection: false
  wgcna: false
  func_annotate: false
  graphlet_counting: true
  graphlet_size: 4
  recursive: true #count lower graphlets as well
  typed_representation: true
  null_model_size: 1000
  coincident_graphlets: false
  
